# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20160916_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.Group', verbose_name='是否摄协'),
        ),
        migrations.AlterField(
            model_name='newmember',
            name='introduction',
            field=models.TextField(verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='newmember',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (0, '女'), (2, '其他')], verbose_name='性别'),
        ),
    ]
