# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_auto_20161016_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='电影自习室')),
                ('description', models.TextField(blank=True, null=True, verbose_name='电影自习室')),
            ],
            options={
                'verbose_name': '电影自习室',
                'verbose_name_plural': '电影自习室',
            },
        ),
        migrations.AddField(
            model_name='newmember',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.Room', verbose_name='电影自习室'),
        ),
    ]
