# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-11 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_auto_20161016_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group1',
            options={'verbose_name': '第一志愿', 'verbose_name_plural': '第一志愿'},
        ),
        migrations.AlterModelOptions(
            name='group2',
            options={'verbose_name': '第二志愿', 'verbose_name_plural': '第二志愿'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '选择舞种', 'verbose_name_plural': '选择舞种'},
        ),
        migrations.RemoveField(
            model_name='newmember',
            name='email',
        ),
        migrations.AddField(
            model_name='newmember',
            name='guanli',
            field=models.IntegerField(choices=[(1, '是'), (0, '否'), (2, '容我想想')], default=1, verbose_name='管理层意向'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newmember',
            name='qq',
            field=models.CharField(default=1, max_length=64, verbose_name='qq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newmember',
            name='wechat',
            field=models.CharField(default=1, max_length=64, verbose_name='微信'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newmember',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.Room', verbose_name='意向舞种'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='选择舞种'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='选择舞种'),
        ),
    ]
