# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-11 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_auto_20170911_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmember',
            name='email',
            field=models.CharField(default=1, max_length=64, verbose_name='邮件'),
            preserve_default=False,
        ),
    ]
