# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-22 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0007_newmember_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmember',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (0, '女'), (2, '仙女')], verbose_name='性别'),
        ),
    ]
